global A;
global b;
global Aeq;
global beq;
global simTime;
global arrivalRate;
global departureRate;
global lInitial;
global noOfLinks;
global noOfPhases;
global weights;
global noOfPhasesInACycle;
global noOfDataSets;
global expertWeights;
global weightsSize;
global minWeight;
global minPhaseLength;
global maxPhaseLength;
global xExpertCombined;
global agentPolicy;
global featureSelection;
global featureSelectionIndex;
global mandatoryPhases;
global phaseSequence;
global observedPhases;
global agentNoOfCycles;
global numberOfIterations;
global allQueuesPower;
global allPhaseLengthsPower;
global generalizedObj;
global intersectionName;
global xIndex;
global policyIndex;
global t;
global l;
global delta;

numberOfIterations = 0;
minWeight = 0.001;
agentNoOfCycles = 3;